# Generated by Django 4.2.3 on 2023-07-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0002_studentdetailsmodel_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('git_hub', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='StudentModel_contact_detail', to='Basics.contactdetailmodel')),
            ],
        ),
    ]
