# Generated by Django 4.2.3 on 2023-07-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0003_contactdetailmodel_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='contact_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentModel_contact_detail', to='Basics.contactdetailmodel'),
        ),
    ]
