# Generated by Django 4.2.3 on 2023-07-29 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0005_organisationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Basics.organisationmodel'),
        ),
    ]
