# Generated by Django 4.2.3 on 2023-07-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0006_studentmodel_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='StudentModel_organisation', to='Basics.organisationmodel'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='StudentModel_subjects', to='Basics.subjectmodel'),
        ),
    ]
